self_balancing_ai:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  wheell_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: motor_l_wheell
    pid: {p: 4.5, i: 10.0, d: 1.0}
  wheelr_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: motor_r_wheelr
    pid: {p: 4.5, i: 10.0, d: 1.0}

